"""
add meals model 3.

Revision ID: b1daf4f9fbbc
Revises: e4ed52a85c03
Create Date: 2026-01-19 04:20:43.592488

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

from config.constants import DB_SCHEMA


# revision identifiers, used by Alembic.
revision: str = 'b1daf4f9fbbc'
down_revision: str | Sequence[str] | None = 'e4ed52a85c03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_main_schema_users_meals_meal_type'), 'users_meals', ['meal_type'], unique=False, schema='main_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_main_schema_users_meals_meal_type'), table_name='users_meals', schema='main_schema')
    # ### end Alembic commands ###
