"""
add user model.

Revision ID: 887754a6121c
Revises: 
Create Date: 2026-01-19 03:58:10.794322

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

from config.constants import DB_SCHEMA


# revision identifiers, used by Alembic.
revision: str = "887754a6121c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=False, comment="Логин пользователя"),
        sa.Column("first_name", sa.String(length=30), nullable=False, comment="Имя пользователя"),
        sa.Column(
            "last_name",
            sa.String(length=30),
            nullable=True,
            comment="Фамилия пользователя",
        ),
        sa.Column(
            "weight",
            sa.Numeric(precision=4, scale=1),
            nullable=False,
            comment="Вес пользователя в кг",
        ),
        sa.Column("height", sa.SmallInteger(), nullable=False, comment="Рост пользователя в см"),
        sa.Column("age", sa.SmallInteger(), nullable=False, comment="Возраст пользователя"),
        sa.Column(
            "sex",
            sa.Enum(
                "MALE",
                "FEMALE",
                name="sex_choices",
                schema=DB_SCHEMA,
                inherit_schema=True,
                length=10,
            ),
            nullable=False,
            comment="Пол пользователя",
        ),
        sa.Column(
            "activity_min",
            sa.SmallInteger(),
            nullable=False,
            comment="Количество минут активности в день",
        ),
        sa.Column("city", sa.String(length=50), nullable=False, comment="Город пользователя"),
        sa.Column(
            "cal_goal",
            sa.SmallInteger(),
            nullable=False,
            comment="Количество калорий в день",
        ),
        sa.Column(
            "water_goal",
            sa.SmallInteger(),
            nullable=False,
            comment="Количество калорий в день",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
        schema=DB_SCHEMA
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users", schema=DB_SCHEMA)
    # ### end Alembic commands ###
