"""
add meals model 2.

Revision ID: e4ed52a85c03
Revises: 55577f815490
Create Date: 2026-01-19 04:18:17.205281

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

from config.constants import DB_SCHEMA


# revision identifiers, used by Alembic.
revision: str = 'e4ed52a85c03'
down_revision: str | Sequence[str] | None = '55577f815490'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_meals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False, comment='Дата приема продукта'),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'SECOND_BREAKFAST', 'LUNCH', 'AFTERNOON_SNACK', 'DINNER', 'SECOND_DINNER', name='meal_choices', schema='main_schema', inherit_schema=True), nullable=False, comment='Тип приема пищи'),
    sa.Column('food_name', sa.String(length=100), nullable=False, comment='Название продукта'),
    sa.Column('amount', sa.Numeric(precision=6, scale=2), server_default='0.00', nullable=False, comment='Количество продукта в граммах'),
    sa.Column('calories', sa.Numeric(precision=6, scale=2), server_default='0.00', nullable=False, comment='Количество калорий'),
    sa.Column('protein', sa.Numeric(precision=6, scale=2), server_default='0.00', nullable=False, comment='Количество белков'),
    sa.Column('carbs', sa.Numeric(precision=6, scale=2), server_default='0.00', nullable=False, comment='Количество углеводов'),
    sa.Column('fat', sa.Numeric(precision=6, scale=2), server_default='0.00', nullable=False, comment='Количество жиров'),
    sa.Column('fiber', sa.Numeric(precision=6, scale=2), server_default='0.00', nullable=False, comment='Количество клетчатки'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ID пользователя'),
    sa.ForeignKeyConstraint(['user_id'], ['main_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='main_schema'
    )
    op.create_index(op.f('ix_main_schema_users_meals_meal_date'), 'users_meals', ['meal_date'], unique=False, schema='main_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_main_schema_users_meals_meal_date'), table_name='users_meals', schema='main_schema')
    op.drop_table('users_meals', schema='main_schema')
    # ### end Alembic commands ###
