"""
add meals model.

Revision ID: 55577f815490
Revises: 887754a6121c
Create Date: 2026-01-19 04:12:54.171427

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

from config.constants import DB_SCHEMA


# revision identifiers, used by Alembic.
revision: str = "55577f815490"
down_revision: str | Sequence[str] | None = "887754a6121c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "calories_goal",
            sa.SmallInteger(),
            nullable=False,
            comment="Количество калорий в день"),
        schema=DB_SCHEMA,
    )
    op.drop_column("users", "cal_goal", schema=DB_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("cal_goal", sa.SMALLINT(), autoincrement=False, nullable=False, comment="Количество калорий в день"), schema=DB_SCHEMA)
    op.drop_column("users", "calories_goal", schema=DB_SCHEMA)
    # ### end Alembic commands ###
